"""
Alembic - Script Mako Template

This is the Alembic script.py.mako file, used for generating migration scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f90f257ea61'
down_revision = '62cfcc98b2dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agents', 'markets', ['assigned_market_id'], ['id'])
    op.add_column('audit_logs', sa.Column('actor_name', sa.String(length=200), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_role', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_province', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_district', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('before_data', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('after_data', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('request_method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('request_path', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True))
    op.add_column('audit_logs', sa.Column('event_type', sa.Enum('NORMAL', 'SECURITY', 'FRAUD', 'ACCESS_VIOLATION', 'SYSTEM_ERROR', name='eventtype'), nullable=True))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(length=36), nullable=True))
    op.add_column('audit_logs', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.alter_column('audit_logs', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_index('idx_audit_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_audit_severity', 'audit_logs', ['severity'], unique=False)
    op.create_foreign_key(None, 'balances', 'merchants', ['merchant_id'], ['id'])
    op.alter_column('jurisdiction_change_requests', 'request_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('CREATE', 'UPDATE', name='requesttype'),
               existing_nullable=True,
               existing_server_default=sa.text("'UPDATE'"))
    op.drop_index(op.f('idx_entity'), table_name='jurisdiction_change_requests')
    op.drop_index(op.f('idx_status'), table_name='jurisdiction_change_requests')
    op.create_foreign_key(None, 'jurisdiction_change_requests', 'users', ['reviewed_by_admin_id'], ['id'])
    op.create_foreign_key(None, 'jurisdiction_change_requests', 'users', ['requested_by_user_id'], ['id'])
    op.drop_column('jurisdiction_change_requests', 'request_notes')
    op.drop_column('markets', 'previous_state')
    op.create_foreign_key(None, 'merchants', 'markets', ['market_id'], ['id'])
    op.drop_index(op.f('idx_municipalities_province'), table_name='municipalities')
    op.create_foreign_key(None, 'municipalities', 'provinces', ['province_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pos_devices', 'province',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'pos_devices', 'agents', ['assigned_agent_id'], ['id'])
    op.drop_column('pos_devices', 'previous_state')
    op.create_foreign_key(None, 'receipts', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'receipts', 'pos_devices', ['pos_id'], ['id'])
    op.create_foreign_key(None, 'receipts', 'merchants', ['merchant_id'], ['id'])
    op.create_foreign_key(None, 'receipts', 'markets', ['market_id'], ['id'])
    op.create_foreign_key(None, 'receipts', 'transactions', ['transaction_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'pos_devices', ['pos_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.add_column('pos_devices', sa.Column('previous_state', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_constraint(None, 'pos_devices', type_='foreignkey')
    op.alter_column('pos_devices', 'province',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'municipalities', type_='foreignkey')
    op.create_index(op.f('idx_municipalities_province'), 'municipalities', ['province_id'], unique=False)
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.add_column('markets', sa.Column('previous_state', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('jurisdiction_change_requests', sa.Column('request_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_constraint(None, 'jurisdiction_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'jurisdiction_change_requests', type_='foreignkey')
    op.create_index(op.f('idx_status'), 'jurisdiction_change_requests', ['status'], unique=False)
    op.create_index(op.f('idx_entity'), 'jurisdiction_change_requests', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('jurisdiction_change_requests', 'request_type',
               existing_type=sa.Enum('CREATE', 'UPDATE', name='requesttype'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'UPDATE'"))
    op.drop_constraint(None, 'balances', type_='foreignkey')
    op.drop_index('idx_audit_severity', table_name='audit_logs')
    op.drop_index('idx_audit_event_type', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('audit_logs', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_column('audit_logs', 'session_id')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'event_type')
    op.drop_column('audit_logs', 'severity')
    op.drop_column('audit_logs', 'request_path')
    op.drop_column('audit_logs', 'request_method')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'after_data')
    op.drop_column('audit_logs', 'before_data')
    op.drop_column('audit_logs', 'actor_district')
    op.drop_column('audit_logs', 'actor_province')
    op.drop_column('audit_logs', 'actor_role')
    op.drop_column('audit_logs', 'actor_name')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    # ### end Alembic commands ###
