"""
Alembic - Script Mako Template

This is the Alembic script.py.mako file, used for generating migration scripts.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cfcc98b2dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.Enum('AGENT', 'ADMIN', 'SYSTEM', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='marketstatus'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AUDITOR', 'FUNCIONARIO', 'SUPERVISOR', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'INATIVO', name='userstatus'), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('assigned_market_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'INATIVO', name='agentstatus'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code')
    )
    op.create_table('merchants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_type', sa.Enum('FIXO', 'AMBULANTE', name='merchanttype'), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('id_document_type', sa.Enum('BI', 'PASSAPORTE', 'DIRE', 'OUTRO', name='iddocumenttype'), nullable=True),
    sa.Column('id_document_number', sa.String(length=50), nullable=True),
    sa.Column('id_document_expiry', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('mobile_operator', sa.Enum('VODACOM', 'TMCEL', 'MOVITEL', name='mobileoperator'), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=False),
    sa.Column('market_id', sa.BigInteger(), nullable=False),
    sa.Column('mpesa_number', sa.String(length=20), nullable=True),
    sa.Column('emola_number', sa.String(length=20), nullable=True),
    sa.Column('mkesh_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('nfc_uid', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'BLOQUEADO', name='merchantstatus'), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfc_uid')
    )
    op.create_table('balances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=14, scale=2), nullable=True),
    sa.Column('last_transaction_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', name='uk_balance_merchant')
    )
    op.create_table('pos_devices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('assigned_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'BLOQUEADO', name='posstatus'), nullable=True),
    sa.Column('last_seen', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('pos_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('payment_method', sa.Enum('DINHEIRO', 'MPESA', 'EMOLA', 'MKESH', name='paymentmethod'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('nfc_uid', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SUCESSO', 'FALHOU', 'CANCELADO', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_uuid')
    )
    op.create_index('idx_tx_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_tx_merchant_date', 'transactions', ['merchant_id', 'created_at'], unique=False)
    op.create_index('idx_tx_pos_date', 'transactions', ['pos_id', 'created_at'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('receipt_code', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('merchant_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('pos_id', sa.BigInteger(), nullable=True),
    sa.Column('market_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('reprint_count', sa.Integer(), nullable=True),
    sa.Column('last_printed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos_devices.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_code')
    )
    op.create_index('idx_receipt_code', 'receipts', ['receipt_code'], unique=False)
    op.create_index('idx_receipt_issued_at', 'receipts', ['issued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receipt_issued_at', table_name='receipts')
    op.drop_index('idx_receipt_code', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('idx_tx_pos_date', table_name='transactions')
    op.drop_index('idx_tx_merchant_date', table_name='transactions')
    op.drop_index('idx_tx_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('pos_devices')
    op.drop_table('balances')
    op.drop_table('merchants')
    op.drop_table('agents')
    op.drop_table('users')
    op.drop_table('markets')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
